name: Deploy a Laymda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-verison: 3.8
    - name: Install Library
      run: |
           cd function
           python -m pip install --upgrade pip
           if [-f requirement.txt ]; then pip install -r requirement.txt -t .; fi
    - name: Create zip file
      run: |
           cd function
           zip -r ../${{github.sha }}.zip .
    - name: Acrhive artifact
      uses: actions/upload-artifact@v4
      with:
        name: zipped-bundle
        path: ${{ github.sha }}.zip
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release from ${{ github.run_number }}
        body: New release for ${{ github.sha }}. Release notes on documentation site
        draft: false
        prerelease: false
    
